--[[
  Формирует шаблон тестового модуля -- файлы с расширением ".h" и ".сс".
--]]

require "libmacro"

if #arg ~= 1 then
  io.write('Usage: lua mktm.lua name\n')
  os.exit()
end

nm = arg[1]

tbl = {
  NM = nm,
  UNM = nm:upper(),
}

-- h

text = [[
// lwml test module: ${NM}
// lwml, (c) ltwood

// This file is automatically generated by 'mktm.lua', no hands!

#ifndef _TEST_${UNM}_
#define _TEST_${UNM}_

#include "defs.h"
#include "mdefs.h"

/*#build_stop*/

namespace lwml_test {

using namespace lwml;

bool test_${NM}();

}; // namespace lwml_test

#endif // _TEST_${UNM}_
]]

io.output('test_' .. nm .. '.h')
io.write(macro.subst(text, tbl))
io.close()

-- cc

text = [[
#include "test_${NM}.h"

/*#build_stop*/

namespace lwml_test {

bool test_${NM}(){
  return true;
}

}; // namespace lwml_test
]]

io.output('test_' .. nm .. '.cc')
io.write(macro.subst(text, tbl))
io.close()
