#!/bin/sh
# Automatically generated by tools/mk_preinstall.lua, no hands!

echo Building installation environment...

UNAME=`uname`
TPU=../third-party

case $UNAME in
  MINGW32_NT*)
    patch --output=$TPU/lua52/src/linit_istools.c $TPU/lua52/src/linit.c $TPU/lua-addons/istools/lua-istools.diff
    cp $TPU/lua-addons/istools/istools.c $TPU/lua52/src
  ;;
  *)
    # sudo apt-get install libreadline-dev
  ;;
esac
SRC_LIST="
  $TPU/lua52/src/lapi.c \
  $TPU/lua52/src/lauxlib.c \
  $TPU/lua52/src/lbaselib.c \
  $TPU/lua52/src/lbitlib.c \
  $TPU/lua52/src/lcode.c \
  $TPU/lua52/src/lcorolib.c \
  $TPU/lua52/src/lctype.c \
  $TPU/lua52/src/ldblib.c \
  $TPU/lua52/src/ldebug.c \
  $TPU/lua52/src/ldo.c \
  $TPU/lua52/src/ldump.c \
  $TPU/lua52/src/lfunc.c \
  $TPU/lua52/src/lgc.c \
  $TPU/lua52/src/liolib.c \
  $TPU/lua52/src/llex.c \
  $TPU/lua52/src/lmathlib.c \
  $TPU/lua52/src/lmem.c \
  $TPU/lua52/src/loadlib.c \
  $TPU/lua52/src/lobject.c \
  $TPU/lua52/src/lopcodes.c \
  $TPU/lua52/src/loslib.c \
  $TPU/lua52/src/lparser.c \
  $TPU/lua52/src/lstate.c \
  $TPU/lua52/src/lstring.c \
  $TPU/lua52/src/lstrlib.c \
  $TPU/lua52/src/ltable.c \
  $TPU/lua52/src/ltablib.c \
  $TPU/lua52/src/ltm.c \
  $TPU/lua52/src/lundump.c \
  $TPU/lua52/src/lvm.c \
  $TPU/lua52/src/lzio.c \
  $TPU/lua52/src/lua.c"

echo Building temp/standalone-lua.exe...

if [[ $UNAME =~ "MINGW32_NT.*" ]]
then
  g++ -O2 -Wall -DLUA_COMPAT_MODULE -otemp/standalone-lua.exe $SRC_LIST $TPU/lua52/src/istools.c $TPU/lua52/src/linit_istools.c
  strip temp/standalone-lua.exe
  rm $TPU/lua52/src/istools.c $TPU/lua52/src/linit_istools.c
else
  g++ -O2 -Wall -DLUA_COMPAT_MODULE -DLUA_USE_LINUX -otemp/standalone-lua $SRC_LIST $TPU/lua52/src/linit.c -ldl -lreadline
  strip temp/standalone-lua
fi
